INSERT INTO USER VALUES (1, 'per@yahoo.no', 'Plk342!s', 'STUDENT');
INSERT INTO USER VALUES (2, 'paul@yahoo.no', 'apKkatt123!', 'STUDENT');
INSERT INTO USER VALUES (3, 'geir@hotmail.com', 'masseRart12', 'TEACHER');
INSERT INTO USER VALUES (4, 'johan@yahoo.no', 'kake123', 'TEACHER')
INSERT INTO USER VALUES (5, 'fredrik@hotmail.no', 'kolboTN214', 'STUDENT')

INSERT INTO LOCATION (id, building, room) VALUES (1, 'Galleriet', '81')
INSERT INTO LOCATION (id, building, room) VALUES (2, 'Galleriet', '82')
INSERT INTO LOCATION (id, building, room) VALUES (3, 'Vulkan', '104')
INSERT INTO LOCATION (id, building, room) VALUES (4, 'Vulkan', '105')

INSERT INTO SUBJECT (id, name, FK_LOCATION) VALUES (1, 'PG5100', 1);
INSERT INTO SUBJECT (id, name, FK_LOCATION) VALUES (2, 'PG6100', 2);
INSERT INTO SUBJECT (id, name, FK_LOCATION) VALUES (3, 'PA1010', 3);
INSERT INTO SUBJECT (id, name, FK_LOCATION) VALUES (4, 'PA3030', 4);
INSERT INTO SUBJECT (id, name, FK_LOCATION) VALUES (5, 'PA9090', 4);


INSERT INTO USR_SUB (SUBJECT_ID, USERS_ID) VALUES (1,1);
INSERT INTO USR_SUB (SUBJECT_ID, USERS_ID) VALUES (2,1);
INSERT INTO USR_SUB (SUBJECT_ID, USERS_ID) VALUES (3,3);
INSERT INTO USR_SUB (SUBJECT_ID, USERS_ID) VALUES (4,3);
INSERT INTO USR_SUB (SUBJECT_ID, USERS_ID) VALUES (5,4);
