CREATE SEQUENCE SEQ_USER
START WITH 5;
CREATE TABLE USER (ID INT PRIMARY KEY, EMAIL VARCHAR (50), PASSWORD VARCHAR (30), TYPE VARCHAR (50) );
INSERT INTO user VALUES (1, 'per@yahoo.no', 'Plk342!s', 'STUDENT');
INSERT INTO user VALUES (2, 'paul@yahoo.no', 'apKkatt123!', 'STUDENT');
COMMIT;
